apiVersion: apps/v1
kind: Deployment
metadata:
  name: kpack-cloud-config-server-deployment
  labels:
    app: kpack-cloud-config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kpack-cloud-config-server
  template:
    metadata:
      labels:
        app: kpack-cloud-config-server
    spec:
      containers:
      - name: kpack-cloud-config-server
        image: registry.dev.redbee.io/kpack-cloud-config-server:latest
        imagePullPolicy: Always
        env:
          - name: "SPRING_PROFILES_ACTIVE"
            value: "test"
        ports:
        - name: httpport
          containerPort: 8888
        readinessProbe:
          httpGet:
            path: /health
            port: httpport
          initialDelaySeconds: 10
          periodSeconds: 20
          failureThreshold: 40
        livenessProbe:
          httpGet:
            path: /health
            port: httpport
          initialDelaySeconds: 10
          periodSeconds: 25
        resources:
          requests:
            memory: "512Mi"
            cpu: "0.5"
          limits:
            memory: "1024Mi"
            cpu: "1"
      imagePullSecrets:
      - name: docker.redbee
